USE ScuolaDb;
GO


SELECT @@VERSION

SELECT @@SERVERNAME

SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME


SELECT *
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME


-- per conoscere le tabelle presenti in un database fornito dal cliente
CREATE PROCEDURE sp_GetAllTabelNames
AS
BEGIN
    SELECT TABLE_NAME
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_TYPE = 'BASE TABLE'
    ORDER BY TABLE_NAME;
END
GO


EXEC sp_GetAllTabelNames;